# Part2

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
X_val = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTValidationX.csv')
y_val = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTValidationY.csv')
X_train = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTTrainXV2.csv')
y_train = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTTrainY.csv')

In [3]:
# Select rf classification algorithm
rf_model = RandomForestClassifier(max_features = 20)

# Train the model
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_val)

<ipython-input-3-59c039a4a82d>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train, y_train)


In [4]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_val, y_pred)
print(cm)

[[1474    0    0    0    1    4   11    0    9    1]
 [   0 1458   17    5    5    2    4    4    2    3]
 [   4    1 1449    5   11    0    2    6   18    4]
 [   5    3   18 1393    0   28    0   17   25   11]
 [   4    3    3    1 1430    0   14    6    6   33]
 [  10    3    5   17    5 1427    7    2   11   13]
 [   5    2    2    0    7   20 1456    0    8    0]
 [   1    5   14    5   12    0    0 1435    3   25]
 [   4   11    8   17   10   23    6    0 1408   13]
 [   5    5    3   23   18    2    0   14   20 1410]]


In [10]:
import numpy as np

sum_off_diag_per_row = np.sum(cm - np.diag(np.diag(cm)), axis=1)

print(sum_off_diag_per_row)

[ 26  42  51 107  70  73  44  65  92  90]


In the confusion matrix, the highest off-diagonal element indicateing that "3" is most likely to be incorrectly classified. It was incorrectly classified as "2" 18 times, incorrectly classified as "5" 28 times, "7" 17 times and 8 "25" times. The most commonly confused digit pairs is "3" and "5".

In [17]:
y_combined = y_val.copy()
y_combined['pred'] = y_pred

# print the updated y_val dataframe
print(y_combined)

       label  pred
0          0     0
1          0     0
2          0     0
3          0     0
4          0     0
...      ...   ...
14995      9     9
14996      9     9
14997      9     9
14998      9     9
14999      9     9

[15000 rows x 2 columns]


In [18]:
indices = y_combined.index[(y_combined.iloc[:, 0] == 3) & (y_combined.iloc[:, 1] == 5)]
print(indices)

Int64Index([4524, 4554, 4555, 4589, 4649, 4667, 4700, 4837, 4875, 4920, 4948,
            5060, 5068, 5107, 5130, 5171, 5182, 5306, 5371, 5420, 5441, 5455,
            5544, 5610, 5723, 5780, 5882, 5964],
           dtype='int64')


Choose first 9 to plot images in R.

# Part 3

In [22]:
X_test = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTTestXRand.csv')
y_test = pd.read_csv('/Users/mc/Desktop/Midterm/MNISTTestYRand.csv')

In [23]:
test_pred = rf_model.predict(X_test)

In [24]:
submission = pd.DataFrame({"Key" : y_test['key'], 'label': test_pred})
submission.to_csv('/Users/mc/Desktop/Midterm/Q6PredictionsMT2.csv', index=False)